### ISSUE TITLE
(Docs): Cannot search for icons that include an uppercase character

### ISSUE THREAD

**Issue by noahsb** [lachlanjc/supercons#1]
Hi, thanks for making this - I love these cute little icons! 

When using the docs site on my phone, (which auto capitalizes the first letter) I noticed that I am always returned 0 search results. I know this is a minor issue, and I'd be happy to send in a PR, but I think anyone using a phone that auto-capitalizes the first letter might get frustrated. Here's an example:

This functions as expected:
![image](https://user-images.githubusercontent.com/49932437/106826479-9d726680-664c-11eb-8bbe-a28a156a9c19.png)

This does not:
![image](https://user-images.githubusercontent.com/49932437/106826506-a9f6bf00-664c-11eb-80f0-d51c2e1dc485.png)

**Comment by lachlanjc** [comment]
Thanks for mentioning! Super quick fix.
